name: Build script

on:							
  push:
    branches: [ "main" ]
      

jobs:
  build:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4		

      - name: build executable	
        run: make -j MatrixMate; ./MatrixMate > testOutput.txt; 	

      - name: build coverage executable
        run: make -j MatrixMateCov; ./MatrixMate; gcov main-main.c

      - name: Upload test results
        uses: actions/upload-artifact@v4	
        with:
          name: Test-Output		
          path: testOutput.txt	

      - name: Upload code coverage
        uses: actions/upload-artifact@v4
        with:
          name: Coverage-Report
          path: main.c.gcov
